// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADJ2JJ0SlSVQ5yE6eW_DiofCTDmVM5vxI',
    appId: '1:937927268337:web:3e3682f2f48e2cbd4cd650',
    messagingSenderId: '937927268337',
    projectId: 'od-delivery-app-56c3a',
    authDomain: 'od-delivery-app-56c3a.firebaseapp.com',
    storageBucket: 'od-delivery-app-56c3a.firebasestorage.app',
    measurementId: 'G-7SK0LD6SX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDijWiDmvVfL6SaaPe4aGbLlFKtwoPMuRo',
    appId: '1:937927268337:android:3a75ca51c02033494cd650',
    messagingSenderId: '937927268337',
    projectId: 'od-delivery-app-56c3a',
    storageBucket: 'od-delivery-app-56c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPsDpALNfNZvlgMz2P1UKuKQEOYuxpYZI',
    appId: '1:937927268337:ios:d6bdcec5db019bc14cd650',
    messagingSenderId: '937927268337',
    projectId: 'od-delivery-app-56c3a',
    storageBucket: 'od-delivery-app-56c3a.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPsDpALNfNZvlgMz2P1UKuKQEOYuxpYZI',
    appId: '1:937927268337:ios:d6bdcec5db019bc14cd650',
    messagingSenderId: '937927268337',
    projectId: 'od-delivery-app-56c3a',
    storageBucket: 'od-delivery-app-56c3a.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADJ2JJ0SlSVQ5yE6eW_DiofCTDmVM5vxI',
    appId: '1:937927268337:web:cb453bb33ed8f3334cd650',
    messagingSenderId: '937927268337',
    projectId: 'od-delivery-app-56c3a',
    authDomain: 'od-delivery-app-56c3a.firebaseapp.com',
    storageBucket: 'od-delivery-app-56c3a.firebasestorage.app',
    measurementId: 'G-99GBL95180',
  );
}
